on:
  push:
jobs:
  semantic-release:
    permissions:
      contents: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: latest
        #[semantic-release]: node version >=20.8.1 is required. Found v18.20.5.
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: bun run test
      - run: bun run build
      - run: bunx semantic-release
        env:
          # reminder to setup read/write permission for this token
          # here: REPO_URL/settings/actions
          # for publishing to GitHub releases
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

          # for publishing to npm
          PHPDIE_NPM_CONFIG_REGISTRY: https://registry.npmjs.org
          PHPDIE_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SNODIE_NPM_CONFIG_REGISTRY: https://registry.npmjs.org
          SNODIE_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
